# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Deploy to the Firebase App Distribution"
    lane :distribute do
        build_ios_app(
            export_method: "ad-hoc",
            export_options: {
                method: "ad-hoc",
                provisioningProfiles: {
                    "app.trainlcd.cs.csapp" => "TrainLCD CSApp AdHoc",
                }
            }
        )
        firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            groups: "CS",
            release_notes: "Lots of amazing new features to test out!",
        )
    end
end
