# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Deploy to the Firebase App Distribution"
    lane :distribute do
        build_android_app(
          task: "assemble",
          build_type: "Release"
         )
        firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            groups: "CSAndroid",
            release_notes: "Lots of amazing new features to test out!",
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end
end
